server:
  port: 8081

spring:
  application:
    name: SavorAI-UserService
  datasource:
    url: jdbc:mysql://localhost:3306/savorAI_user?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:appsavorai@gmail.com}
    password: ${MAIL_PASSWORD:pxdw zfyj qchv xbwp}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Application URL
app:
  url: http://localhost:8081
  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}

# Basic logging
logging:
  level:
    root: INFO
    dev.idachev.userservice: DEBUG

jwt:
  secret: ${JWT_SECRET:cHxkdyB6ZnlqIHFjaHYgeGJ3cABwW5zaGdqaGQK2j1mn2j3bas9}
  expiration: 86400000 # 24 hours

security:
  allowed-public-apis:
    - /api/v1/user/register
    - /api/v1/user/login
    - /api/v1/user/verify/**
    - /api/v1/user/reset-password-request
    - /api/v1/user/reset-password

cors:
  allowed-origins: http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type
  allow-credentials: true 