server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /

spring:
  application:
    name: user-service
  
  # Database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/savorAI_user?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA configuration  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  
  # Email service configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Frontend application configuration
app:
  # Service URL (used for email verification links)
  service:
    url: ${APP_SERVICE_URL:http://localhost:8081}
  frontend:
    url: ${APP_FRONTEND_URL:http://localhost:5173}
    routes:
      login: /login
      register: /register

# Security configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours
  blacklist:
    cleanup-interval: ${JWT_BLACKLIST_CLEANUP_INTERVAL:3600} # Cleanup interval in seconds (1 hour)

# CORS configuration
cors:
  allowed-origins: ${APP_FRONTEND_URL:http://localhost:5173}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type
  allow-credentials: true

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
  packages-to-scan: dev.idachev.userservice.web 