server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: user-service
  
  # Database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/savorAI_user?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA configuration  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  
  # Email service configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Frontend application configuration
app:
  frontend:
    url: http://localhost:5173
    routes:
      login: /login
      register: /register

# Security configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours

# CORS configuration
cors:
  allowed-origins: http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type
  allow-credentials: true

# Logging configuration
logging:
  level:
    root: INFO
    dev.idachev.userservice: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG 